apiVersion: v1
kind: ConfigMap
metadata:
  name: thiru-order-config
  namespace: thiru-helm-argo
data:
  DATABASE_URL: {{ .Values.config.database_url }}
  PAYMENT_GATEWAY: {{ .Values.config.payment_gateway }}
  ORDER_EXPIRY: "24h"
  SHOPPING_CART_SERVICE_URL: "http://shopping-cart-service"