apiVersion: v1
kind: Service
metadata:
  name: thiru-order-service
spec:
  selector:
    app: thiru-order
  ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}